# Generated by Django 6.0.2 on 2026-08-23 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('representative_name', models.CharField(help_text='Nome da família ou do responsável principal.', max_length=255, verbose_name='Nome do Responsável / Família')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('cep', models.CharField(db_index=True, help_text='CEP no formato 00000-000 ou 00000000.', max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro / Rua')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Familiar Mensal (R$)')),
                ('housing_status', models.CharField(blank=True, help_text='Ex: Própria, Alugada, Cedida, Ocupação.', max_length=100, verbose_name='Situação de Moradia')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Socioeconômicas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('unit', models.ForeignKey(help_text='Unidade que acompanha e atende esta família.', on_delete=django.db.models.deletion.PROTECT, related_name='families', to='organizational.organizationalunit', verbose_name='Unidade Responsável')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['-registration_date', 'representative_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('inclusion_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Inclusão')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Solteiro(a)'), ('MARRIED', 'Casado(a)'), ('DIVORCED', 'Divorciado(a)'), ('WIDOWED', 'Viúvo(a)'), ('STABLE_UNION', 'União Estável)'), ('OTHER', 'Outro')], default='SINGLE', max_length=30, verbose_name='Estado Civil')),
                ('kinship', models.CharField(choices=[('HEAD', 'Responsável Familiar'), ('SPOUSE', 'Cônjuge / Companheiro(a)'), ('SON_DAUGHTER', 'Filho(a)'), ('PARENT', 'Pai / Mãe'), ('SIBLING', 'Irmão / Irmã'), ('GRANDPARENT', 'Avô / Avó'), ('GRANDCHILD', 'Neto(a)'), ('OTHER', 'Outro Vínculo')], default='OTHER', max_length=30, verbose_name='Grau de Parentesco')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Membro')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='beneficiaries.family', verbose_name='Família')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'ordering': ['inclusion_date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['unit', 'is_active'], name='beneficiari_unit_id_dc3b00_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['cep'], name='beneficiari_cep_b56f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['representative_name'], name='beneficiari_represe_dfad7b_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'kinship'], name='beneficiari_family__46d8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['cpf'], name='beneficiari_cpf_b11165_idx'),
        ),
    ]
