# Generated by Django 6.0.2 on 2026-08-23 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('PASTOR', 'Pastor'), ('DIRECTOR', 'Diretor'), ('SECRETARY', 'Secretário'), ('ASSISTANT', 'Auxiliar')], default='ASSISTANT', max_length=30, verbose_name='Papel / Função')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizational.organizationalunit', verbose_name='Unidade Organizacional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo de Usuário na Unidade',
                'verbose_name_plural': 'Vínculos de Usuários nas Unidades',
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_un_user_id_3273cd_idx'), models.Index(fields=['unit', 'is_active'], name='accounts_un_unit_id_cf1d2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'unit'), name='unique_user_unit_membership')],
            },
        ),
    ]
