# Generated by Django 6.0.2 on 2026-08-23 22:52

import benefits.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Benefício')),
                ('year', models.PositiveIntegerField(db_index=True, default=benefits.models.get_current_year, verbose_name='Ano de Referência')),
                ('benefit_type', models.CharField(choices=[('AJUDA', 'Ajuda de Custo / Financeira'), ('CAMPANHA', 'Campanha Sazonal (Natal, Inverno, etc.)'), ('CESTA_BASICA', 'Cesta Básica / Alimentos'), ('PROFISSIONALIZANTE', 'Curso Profissionalizante'), ('ROUPAS', 'Roupas e Calçados'), ('OUTRO', 'Outro')], default='CESTA_BASICA', max_length=30, verbose_name='Tipo de Benefício')),
                ('period', models.CharField(choices=[('UNICO', 'Único (Pontual)'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='UNICO', max_length=30, verbose_name='Periodicidade')),
                ('scope', models.CharField(choices=[('FAMILIAR', 'Familiar'), ('INDIVIDUAL', 'Individual')], db_index=True, default='FAMILIAR', help_text='Familiar: concedido à família como um todo (1x). Individual: concedido a um membro específico.', max_length=20, verbose_name='Escopo da Concessão')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição e Critérios')),
                ('quantity_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Total Disponível (Opcional)')),
                ('unit', models.ForeignKey(help_text='Unidade que criou e gerencia este benefício.', on_delete=django.db.models.deletion.PROTECT, related_name='created_benefits', to='organizational.organizationalunit', verbose_name='Unidade de Origem')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('granted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora da Concessão')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade Concedida')),
                ('notes', models.TextField(blank=True, verbose_name='Observações da Concessão')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='benefits.benefit', verbose_name='Benefício Concedido')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_grants', to='beneficiaries.family', verbose_name='Família Beneficiada')),
                ('grant_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_benefit_grants', to='organizational.organizationalunit', verbose_name='Unidade Concessora')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_benefits', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por (Usuário)')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefit_grants', to='beneficiaries.familymember', verbose_name='Membro Beneficiado (se escopo individual)')),
            ],
            options={
                'verbose_name': 'Concessão de Benefício',
                'verbose_name_plural': 'Concessões de Benefícios',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='benefit',
            index=models.Index(fields=['unit', 'is_active'], name='benefits_be_unit_id_a1a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='benefit',
            index=models.Index(fields=['scope', 'is_active'], name='benefits_be_scope_d7725b_idx'),
        ),
        migrations.AddIndex(
            model_name='benefit',
            index=models.Index(fields=['year', 'benefit_type'], name='benefits_be_year_93b333_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitgrant',
            index=models.Index(fields=['benefit', 'granted_at'], name='benefits_be_benefit_73a741_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitgrant',
            index=models.Index(fields=['family', 'granted_at'], name='benefits_be_family__f4d32d_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitgrant',
            index=models.Index(fields=['grant_unit', 'granted_at'], name='benefits_be_grant_u_88e318_idx'),
        ),
        migrations.AddConstraint(
            model_name='benefitgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', True)), fields=('benefit', 'family'), name='unique_familiar_benefit_grant_per_family'),
        ),
    ]
