# Generated by Django 6.0.2 on 2026-08-23 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome descritivo da unidade (ex: Igreja Central de Salvador).', max_length=255, verbose_name='Nome da Unidade')),
                ('code', models.CharField(blank=True, help_text='Código identificador único opcional (ex: IAG-001).', max_length=50, null=True, unique=True, verbose_name='Código da Unidade')),
                ('unit_type', models.CharField(choices=[('UNION', 'União'), ('CONFERENCE', 'Associação / Missão'), ('DISTRICT', 'Distrito'), ('LOCAL_CHURCH', 'Igreja Local'), ('OTHER', 'Outro')], default='LOCAL_CHURCH', max_length=30, verbose_name='Tipo de Unidade')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('parent', models.ForeignKey(blank=True, help_text='Unidade hierarquicamente superior. Deixe em branco se for a raiz.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizational.organizationalunit', verbose_name='Unidade Superior (Pai)')),
            ],
            options={
                'verbose_name': 'Unidade Organizacional',
                'verbose_name_plural': 'Unidades Organizacionais',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='organizatio_parent__687e41_idx'), models.Index(fields=['unit_type', 'is_active'], name='organizatio_unit_ty_f1c48c_idx')],
            },
        ),
    ]
